#!/bin/bash
# Audio-friendly summary of Base bridging docs for vision-impaired user
# Focuses ONLY on what they need to know to claim their stuck WETH

echo ""
echo "[VOICE] ======== BASE BRIDGING DOCS - ESSENTIAL ONLY ========"
echo ""
echo "[VOICE] FOR YOUR SITUATION: You already deposited WETH to Base 2 days ago."
echo "[VOICE] The transaction succeeded on Ethereum. Now you need to CLAIM it on Base."
echo ""
echo "[VOICE] ======== KEY FACTS FROM BASE DOCS ========"
echo ""
echo "[VOICE] 1. The old bridge at bridge.base.org is DEPRECATED. DO NOT USE IT."
echo "[VOICE] 2. Use these INSTEAD to claim your deposit:"
echo "[VOICE]    - SUPERBRIDGE: https://superbridge.app/base"
echo "[VOICE]    - BRID.GG: https://brid.gg/base"
echo ""
echo "[VOICE] 3. HOW TO CLAIM (STEP-BY-STEP):"
echo "[VOICE]    a. OPEN YOUR WALLET (Metamask, etc.)"
echo "[VOICE]    b. SWITCH TO BASE NETWORK"
echo "[VOICE]       Network Name: Base"
echo "[VOICE]       RPC URL: https://mainnet.base.org"
echo "[VOICE]       Chain ID: 8453"
echo "[VOICE]    c. GO TO https://superbridge.app/base"
echo "[VOICE]    d. CONNECT YOUR WALLET (SAME ADDRESS USED FOR DEPOSIT)"
echo "[VOICE]    e. CLICK THE 'HISTORY' TAB"
echo "[VOICE]    f. LOOK FOR YOUR MAR 20 DEPOSIT (0.0297375 WETH)"
echo "[VOICE]    g. IF YOU SEE A 'CLAIM' BUTTON NEXT TO IT, CLICK IT"
echo "[VOICE]    h. CONFIRM THE TRANSACTION IN YOUR WALLET"
echo ""
echo "[VOICE] 4. AFTER CLAIMING, CHECK YOUR BALANCE:"
echo "[VOICE]    - WETH ON BASE CONTRACT: 0x4200000000000000000000000000000000000006"
echo "[VOICE]    - SYMBOL: WETH"
echo "[VOICE]    - DECIMALS: 18"
echo ""
echo "[VOICE] ======== IF SUPERBRIDGE DOESN'T SHOW YOUR DEPOSIT ========"
echo ""
echo "[VOICE] TRY BRID.GG INSTEAD:"
echo "[VOICE]    - GO TO https://brid.gg/base"
echo "[VOICE]    - REPEAT STEPS B-H ABOVE"
echo ""
echo "[VOICE] ======== VERIFY WITHOUT UI (AUDIO-FRIENDLY) ========"
echo ""
echo "[VOICE] TO CHECK IF FUNDS ARRIVED ON BASE AFTER CLAIMING:"
echo "[VOICE]    RUN THIS COMMAND IN YOUR TERMINAL:"
echo "[VOICE]    curl -s \"https://api.basescan.org/api?module=account&action=tokenbalance&contractaddress=0x4200000000000000000000000000000000000006&address=0xC649A2F94AFc4e5649d3d575d16e739e70b2ba2f\" | grep -o '\"result\":\"[^\"]*\"' | cut -d'\"' -f4 | xargs -I{} echo \"[VOICE] Your Base WETH balance: {}/1000000000000000000 WETH\" | bc -l"
echo "[VOICE]    (This will speak your balance aloud)"
echo ""
echo "[VOICE] ======== IMPORTANT REMINDERS ========"
echo ""
echo "[VOICE] • Your funds are SAFE. They are NOT lost."
echo "[VOICE] • They are held securely by the bridge system until you claim them."
echo "[VOICE] • Current gas prices you see (0.03-0.05 Gwei) only affect NEW transactions."
echo "[VOICE] • They do NOT prevent you from claiming already-deposited funds."
echo "[VOICE] • Claiming usually requires ONLY ONE transaction (the claim itself)."
echo ""
echo "[VOICE] ======== YOUR ACTION PLAN ========"
echo ""
echo "[VOICE] 1. SWITCH WALLET TO BASE NETWORK"
echo "[VOICE] 2. VISIT https://superbridge.app/base"
echo "[VOICE] 3. CONNECT WALLET → HISTORY TAB → LOOK FOR DEPOSIT → CLAIM IF AVAILABLE"
echo "[VOICE] 4. IF NO CLAIM BUTTON, TRY https://brid.gg/base INSTEAD"
echo "[VOICE] 5. AFTER CLAIMING, RUN THE BALANCE CHECK COMMAND ABOVE"
echo "[VOICE] 6. YOU SHOULD SEE ~0.0297 WETH WORTH ~$61"
echo ""
echo "[VOICE] ======== END OF ESSENTIAL INFO ========"
echo ""
