# Consolidate Projects Script
# Moves key files into unified S:\workspace structure

param(
    [switch]$WhatIf
)

$ErrorActionPreference = "Continue"

$Root = "S:\workspace"
$Backend = "S:\snac-v2\snac-v2\backend"

# Create directories
@("projects\snac-v2", "projects\cuda-bench", "agents\kilo", "docs", "tools", "data", "cache", "scratch") | ForEach-Object {
    $path = Join-Path $Root $_
    if (!(Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
        Write-Host "Created: $path" -ForegroundColor Cyan
    }
}

Write-Host "`n=== Consolidating files ===`n" -ForegroundColor Yellow

# 1. Copy IDE blueprints
$IDEFiles = @(
    "IDEblueprintagain.md",
    "IDEmoreblueprintideas.md"
)

foreach ($f in $IDEFiles) {
    $src = Join-Path $Backend $f
    $dst = Join-Path $Root "docs\IDE\$f"
    if (Test-Path $src) {
        $dir = Split-Path $dst
        if (!(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Copy-Item $src -Destination $dst -Force
        Write-Host "Copied: $f -> docs\IDE\" -ForegroundColor Green
    }
}

# 2. Copy Kilo upgrade files
$KiloFiles = @(
    "kiloupgrades2.md",
    "kiloupgrades3.md",
    "kiloupgrades4.md",
    "kiloupgrades5.md",
    "kiloupgrades6.md",
    "kilomulti.md",
    "kilobrowserautonomation.md",
    "kiloboom.md"
)

foreach ($f in $KiloFiles) {
    $src = Join-Path $Backend $f
    $dst = Join-Path $Root "docs\kilo\$f"
    if (Test-Path $src) {
        $dir = Split-Path $dst
        if (!(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Copy-Item $src -Destination $dst -Force
        Write-Host "Copied: $f -> docs\kilo\" -ForegroundColor Green
    }
}

# 3. Copy CUDA benchmark
$cudaSrc = Join-Path $Backend "we"
$cudaDst = Join-Path $Root "projects\cuda-bench"
if (Test-Path $cudaSrc) {
    Copy-Item $cudaSrc -Destination $cudaDst -Recurse -Force
    Write-Host "Copied: we -> projects\cuda-bench\" -ForegroundColor Green
}

# 4. Copy agent-system
$agentSrc = Join-Path $Backend "agent-system"
$agentDst = Join-Path $Root "agents\kilo"
if (Test-Path $agentSrc) {
    Copy-Item $agentSrc -Destination $agentDst -Recurse -Force
    Write-Host "Copied: agent-system -> agents\kilo\" -ForegroundColor Green
}

# 5. Copy snac-v2 backend
$snacSrc = $Backend
$snacDst = Join-Path $Root "projects\snac-v2"
if (Test-Path $snacSrc) {
    Copy-Item $snacSrc -Destination $snacDst -Recurse -Force -Exclude "node_modules","we","agent-system"
    Write-Host "Copied: snac-v2 -> projects\snac-v2\" -ForegroundColor Green
}

Write-Host "`n=== Creating workspace manifest ===`n" -ForegroundColor Yellow

# Create manifest
$Manifest = @"
# WORKSPACE MANIFEST
# Auto-generated: $(Get-Date -Format "yyyy-MM-dd HH:mm")

## Root: $Root

### Directories
- projects/     - All project code
- agents/      - Agent configurations
- docs/        - Documentation
- tools/       - Automation scripts
- data/        - Data files
- cache/       - Temporary/cache
- scratch/     - Work in progress

### Quick Links
- [IDE Docs](docs/IDE/)
- [Kilo Docs](docs/kilo/)
- [CUDA Bench](projects/cuda-bench/)
- [Kilo Agents](agents/kilo/)

---

Generated by setup-unified-workspace.ps1
"@

$Manifest | Out-File -FilePath (Join-Path $Root "MANIFEST.md") -Encoding UTF8

Write-Host "Created: MANIFEST.md" -ForegroundColor Green

Write-Host "`n=== DONE ===" -ForegroundColor Green
Write-Host "Workspace ready at: $Root"
