# Unified Workspace Setup Script
# Run this to organize your projects into a single mega-workspace

param(
    [string]$Root = "S:\workspace",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

Write-Host "======================================"
Write-Host "  UNIFIED WORKSPACE SETUP"
Write-Host "======================================"
Write-Host ""

# Define source locations to scan
$Sources = @(
    "S:\snac-v2\snac-v2\backend",
    "S:\workspace",
    "C:\Users\seand\OneDrive\workspace\_root\mev-swarm-temp"
)

# Define target structure
$Structure = @{
    "projects" = @()
    "agents" = @()
    "docs" = @()
    "tools" = @()
    "data" = @()
    "cache" = @()
    "scratch" = @()
}

function Get-FolderSize {
    param([string]$Path)
    if (Test-Path $Path) {
        (Get-ChildItem $Path -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum / 1MB
    } else { 0 }
}

function Invoke-MoveFile {
    param([string]$From, [string]$To)
    
    $dir = Split-Path $To -Parent
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    
    if ($DryRun) {
        Write-Host "[DRY RUN] Would move: $From -> $To" -ForegroundColor Yellow
    } else {
        Move-Item -Path $From -Destination $To -Force
        Write-Host "[MOVED] $From -> $To" -ForegroundColor Green
    }
}

Write-Host "Creating root structure..." -ForegroundColor Cyan

# Create root directories
@("projects", "agents", "docs", "tools", "data", "cache", "scratch") | ForEach-Object {
    $path = Join-Path $Root $_
    if (!(Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
        Write-Host "  Created: $path"
    }
}

Write-Host ""
Write-Host "Scanning source locations..." -ForegroundColor Cyan

# Scan and categorize files
$AllFiles = @()

foreach ($source in $Sources) {
    if (Test-Path $source) {
        Write-Host "  Scanning: $source"
        $files = Get-ChildItem $source -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in @(".md", ".js", ".ts", ".json", ".py", ".cu", ".exe") }
        $AllFiles += $files
    }
}

Write-Host "  Found $($AllFiles.Count) files total"
Write-Host ""

# Categorize files
$Categories = @{
    "IDE" = @("IDEblueprint", "IDEmoreblueprint", "MONACO_IDE")
    "Kilo" = @("kilo", "kilomulti", "kiloboom", "kilobrowser")
    "Upgrades" = @("kiloupgrade", "jiloupgrades")
    "CUDA" = @("cuda", "benchmark", "gptcuda", "nvprof")
    "Agent" = @("agent", "mesh", "orchestrator")
    "Docs" = @("GUIDE", "README", "ARCHITECTURE", "DIRECTIVE")
    "Config" = @(".json", ".ts", ".js", ".yaml", ".yml")
}

$Results = @{}

foreach ($file in $AllFiles) {
    $matched = $false
    
    foreach ($cat in $Categories.Keys) {
        foreach ($pattern in $Categories[$cat]) {
            if ($file.Name -like "*$pattern*") {
                if (!$Results[$cat]) { $Results[$cat] = @() }
                $Results[$cat] += $file
                $matched = $true
                break
            }
        }
        if ($matched) { break }
    }
    
    if (!$matched) {
        if (!$Results["Other"]) { $Results["Other"] = @() }
        $Results["Other"] += $file
    }
}

# Display results
Write-Host "File categorization:" -ForegroundColor Cyan
foreach ($cat in $Results.Keys | Sort-Object) {
    $count = $Results[$cat].Count
    Write-Host "  $cat : $count files"
}

Write-Host ""
Write-Host "Creating workspace index..." -ForegroundColor Cyan

# Generate index
$IndexFile = Join-Path $Root "WORKSPACE_INDEX.md"
$IndexContent = @"
# WORKSPACE INDEX

Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm")

## File Counts

| Category | Count |
|----------|-------|
$($Results.Keys | ForEach-Object { "| $_ | $($Results[$_].Count) |" })

## Key Files

### IDE Blueprints
$($Results["IDE"] | ForEach-Object { "- $($_.FullName)" })

### Kilo Files
$($Results["Kilo"] | ForEach-Object { "- $($_.FullName)" })

### CUDA
$($Results["CUDA"] | ForEach-Object { "- $($_.FullName)" })

---

*Auto-generated by workspace setup*
"@

$IndexContent | Out-File -FilePath $IndexFile -Encoding UTF8
Write-Host "  Created: $IndexFile"

Write-Host ""
Write-Host "======================================" -ForegroundColor Green
Write-Host "  SETUP COMPLETE"
Write-Host "======================================"
Write-Host ""
Write-Host "Run with -DryRun to preview changes"
Write-Host "Root workspace: $Root"
